const EndPoints = {
  customer: {
    corp: "/customer/corptaglist",
    generateOtp: "/customer/generateotp",
    verifyOty: "/customer/verifyotp",
    register: "/customer/auth/register",
    login: "/customer/auth/login",
    buytags: "/customer/buy/tags",
    verifyOtp: '/customer/verifyotp',
    getVoiceMail: '/customer/voicemail',
    changePassword: "/customer/change-password",
    getSchedular: "/customer/corp-subscriber",
    IndividualPostSchedular: "/individual/call-scheduling",
    getReserve: "/customer/reserve/tags",
    verifyAccount: "/customer/auth/very/accounts",
    getFilter: "/customer/unique-tag-digits",
    forgotPassword: "/customer/auth/forgot/password",
    IndividualforgotPassword: "/individual/auth/forgot/password",
    createOrder: "/customer/order",
    newPassword: "/customer/auth/update/password",
    uploadDocument: "/customer/document/save",
    updateDocument: "/customer/document/update",
    GetAllNumbers: (customerId) => `/customer/phone-number?corp_customer_account_id=${customerId}`,
    CreateNumber: `/customer/phone-number`,
    DeleteNumber: (selectedNumber) => `/customer/phone-number/${selectedNumber}`,
    premiumTag: "/customer/premium-tag-list",
    individualRegister: "/individual/auth/register",
    tagListCustomer: "/individual/tag-list",
    getFilterCustomer: "/individual/unique-tag-digits",
    buytagsCustomer: "/individual/reserve/buy",
    getReserveTagsCustomer: "/individual/reserve/tags",
    getBlockNumber: "/customer/block-numbers",
    saveIndividualBlockNumber: "/individual/block-number",
    getIndividualBlockNumber: "/individual/block-number",
    saveBlockNumber: "/customer/block-numbers",
    individualUnSun: "/individual/unsubscribe",
    changePasswordCustomer: "/individual/change-password",
    updateProfileCustomer: "/individual/update-profile",
    deleteBlockNumber: (id) => `/customer/block-numbers/${id}`,
    individualdeleteBlockNumber: (id) => `/individual/block-number/${id}`,
    updateProfile: (slug) => `/customer/updatecustomer/${slug}`,
    updateIndividualProfile: (slug) => `/individual/updatecustomer/${slug}`,
    individualchangeNumberSaving: "individual/change-number",
    corporatechangeNumberSaving: "customer/change-number",
    updateStatus: `/customer/close-account`,
    createMandate: "/individual/create-mandate",
    createMandateCorp: "/customer/create-mandate"
  },
};

export default EndPoints;
