const EndPoints = {
  customer: {
    corp: "/customer/corptaglist",
    generateOtp: "/customer/generateotp",
    verifyOty: "/customer/verifyotp",
    register: "/customer/auth/register",
    login: "/customer/auth/login",
    buytags: "/customer/buy/tags",
    verifyOtp: '/customer/verifyotp',
    getVoiceMail: '/customer/voicemail',
    changePassword: "/customer/change-password",
    getSchedular: "/customer/corp-subscriber",
    IndividualPostSchedular: "/individual/call-scheduling",
    getReserve: "/customer/reserve/tags",
    verifyAccount: "/customer/auth/very/accounts",
    getFilter: "/customer/unique-tag-digits",
    forgotPassword: "/customer/auth/forgot/password",
    IndividualforgotPassword: "/individual/auth/forgot/password",
    createOrder: "/customer/order",
    getProfileDetail: "/customer/detail",
    newPassword: "/customer/auth/update/password",
    uploadDocument: "/customer/document/save",
    updateDocument: "/customer/document/update",
    GetAllNumbers: (customerId) => `/customer/phone-number?corp_customer_account_id=${customerId}`,
    CreateNumber: `/customer/phone-number`,
    ChangeNumber: `/customer/change-msisdn`,
    ChangeNumberOutstandingFee: `/customer/change-msisdn-outstanding-fee`,
    DeleteNumber: (selectedNumber) => `/customer/phone-number/${selectedNumber}`,
    premiumTag: "/customer/premium-tag-list",
    individualRegister: "/individual/auth/register",
    tagListCustomer: "/individual/tag-list",
    getFilterCustomer: "/individual/unique-tag-digits",
    buytagsCustomer: "/individual/reserve/buy",
    getReserveTagsCustomer: "/individual/reserve/tags",
    getBlockNumber: "/customer/block-numbers",
    getWhiteListNumber: "/customer/whitelist",
    addWhiteList: "/customer/add-whitelist",
    deleteWhiteList: (id) => `/customer/remove-whitelist/${id}`,
    saveIndividualBlockNumber: "/individual/block-number",
    getIndividualBlockNumber: "/individual/block-number",
    saveBlockNumber: "/customer/block-numbers",
    setCallpin: "/customer/setcallpin",
    individualUnSun: "/individual/unsubscribe",
    changePasswordCustomer: "/individual/change-password",
    updateProfileCustomer: "/individual/update-profile",
    deleteBlockNumber: (id) => `/customer/block-numbers/${id}`,
    individualdeleteBlockNumber: (id) => `/individual/block-number/${id}`,
    updateProfile: (slug) => `/customer/updatecustomer/${slug}`,
    updateIndividualProfile: (slug) => `/individual/updatecustomer/${slug}`,
    individualchangeNumberSaving: "individual/change-number",
    corporatechangeNumberSaving: "customer/change-number",
    updateStatus: `/customer/close-account`,
    individualCloseAccount: `/individual/close-account`,
    createMandate: "/individual/create-mandate",
    addWhiteListIndividual: "/individual/add-whitelist",
    getWhiteListNumberIndividual: "/individual/whitelist",
    deleteWhiteListIndividual: (id) => `/individual/remove-whitelist/${id}`,
    setCallpinIndividual: "/individual/setcallpin",
    createMandateCorp: "/customer/create-mandate",
    getIndustries: "/customer/industries",
    getRegions: "/customer/regions",
    guestVerifyOtp: "/customer/guest/verifyotp",
    guestBlockNumbers: "/customer/guest/block-numbers",
    guestDeleteBlockNumber: (id) => `/customer/guest/block-numbers/${id}`,
    validateToken: "/customer/payment-due/validate-token",

    // New Security End Points 
    newSecurityEndPoints: {
      individual: {
        signUp: "/individual/auth/sign-up",
        updateProfile: "/individual/profile/update",
        getProfile: "/individual/profile",
        updatePassword: "/individual/password/update",
        getReserveTags: "/individual/reserve/tags",
      },
      corporate: {
        checkDocumentStatus: "/customer/verify-document-status",
        updateProfile:"/customer/update/customer-accounts",
        getProfile: "/customer/account-detail",
        uploadDocument: "/customer/documents/upload",
        updateDocument: "/customer/documents/update",
      },
    },
  },
};

export default EndPoints;
